let actionTypes = {
    //LOGIN ACTIONS
    FAZER_LOGIN: 'LOGIN',
    FAZER_LOGOUT: 'FAZER_LOGOUT',
    LOGOUT_REALIZADO: 'LOGOUT_REALIZADO',
    LOGIN_REALIZADO: 'LOGIN_REALIZADO',

    //FORNECEDOR ACTIONS
    LOGIN_FORNECEDOR: 'LOGIN_FORNECEDOR',
    INFORMACOES_FORNECEDOR: 'INFORMACOES_FORNECEDOR',
    ENDERECO_FORNECEDOR: 'ENDERECO_FORNECEDOR',
    SALVAR_FAVORECIDO: 'SALVAR_FAVORECIDO',
    CADASTRO_FORNECEDOR_REALIZADO: 'CADASTRO_FORNECEDOR_REALIZADO',

    //CARRINHO ACTIONS
    RESUMO_PEDIDOS_ENCONTRADOS: 'RESUMO_PEDIDOS_ENCONTRADOS',

    //CARDAPIO ACTIONS
    CARDAPIOS_ENCONTRADOS: 'CARDAPIOS_ENCONTRADOS',
    CARDAPIO_CRIADO: 'CARDAPIO_CRIADO',
    CARDAPIO_ENCONTRADO: 'CARDAPIO_ENCONTRADO',
    CATEGORIA_CRIADA: 'CATEGORIA_CRIADA',
    CATEGORIA_REMOVIDA: 'CATEGORIA_REMOVIDA',
    SUBCATEGORIAS_ENCONTRADA: 'SUBCATEGORIAS_ENCONTRADA',
    PRODUTO_ADICIONADO: 'PRODUTO_ADICIONADO',
    PRODUTO_REMOVIDO: 'PRODUTO_REMOVIDO',
    IMAGEM_BAIXADA: 'IMAGEM_BAIXADA',
    CARDAPIO_REMOVIDO: 'CARDAPIO_REMOVIDO',
    
    //ERRO ACTIONS
    APRESENTAR_ERROS: 'APRESENTAR_ERROS'
}


export default actionTypes;