let actionTypes = {
    //LOGIN ACTIONS
    FAZER_LOGIN: 'LOGIN',
    FAZER_LOGOUT: 'FAZER_LOGOUT',
    LOGOUT_REALIZADO: 'LOGOUT_REALIZADO',
    LOGIN_REALIZADO: 'LOGIN_REALIZADO',

    //FORNECEDOR ACTIONS
    LOGIN_FORNECEDOR: 'LOGIN_FORNECEDOR',
    INFORMACOES_FORNECEDOR: 'INFORMACOES_FORNECEDOR',
    ENDERECO_FORNECEDOR: 'ENDERECO_FORNECEDOR',
    SALVAR_FAVORECIDO: 'SALVAR_FAVORECIDO',
    CADASTRO_FORNECEDOR_REALIZADO: 'CADASTRO_FORNECEDOR_REALIZADO',

    //CARRINHO ACTIONS
    RESUMO_PEDIDOS_ENCONTRADOS: 'RESUMO_PEDIDOS_ENCONTRADOS',
    PEDIDOS_PENDENTE_PREPARACAO_ENCONTRADOS: 'PEDIDOS_PENDENTE_PREPARACAO_ENCONTRADOS',
    PEDIDOS_EM_PREPARO_ENCONTRADOS: 'PEDIDOS_EM_PREPARO_ENCONTRADOS',
    PEDIDOS_CONCLUIDOS_ENCONTRADOS: 'PEDIDOS_CONCLUIDOS_ENCONTRADOS',

    //CARDAPIO ACTIONS
    CARDAPIOS_ENCONTRADOS: 'CARDAPIOS_ENCONTRADOS',
    CARDAPIO_CRIADO: 'CARDAPIO_CRIADO',
    CARDAPIO_ENCONTRADO: 'CARDAPIO_ENCONTRADO',
    CATEGORIA_CRIADA: 'CATEGORIA_CRIADA',
    CATEGORIA_REMOVIDA: 'CATEGORIA_REMOVIDA',
    SUBCATEGORIAS_ENCONTRADA: 'SUBCATEGORIAS_ENCONTRADA',
    PRODUTO_ADICIONADO: 'PRODUTO_ADICIONADO',
    PRODUTO_REMOVIDO: 'PRODUTO_REMOVIDO',
    IMAGEM_BAIXADA: 'IMAGEM_BAIXADA',
    CARDAPIO_REMOVIDO: 'CARDAPIO_REMOVIDO',
    PRODUTOS_MELHORES_AVALIADOS: 'PRODUTOS_MELHORES_AVALIADOS',

    //CADASTRO ACTIONS
    CADASTRO_ENCONTRADO: 'CADASTRO_ENCONTRADO',
    HORARIOS_FUNCIONAMENTO_ENCONTRADO: 'HORARIOS_FUNCIONAMENTO_ENCONTRADO',
    HORARIOS_DIFERENCIADOS_ENCONTRADO: 'HORARIOS_DIFERENCIADOS_ENCONTRADO',
    HORARIO_DIFERENCIADO_ADICIONADO: 'HORARIO_DIFERENCIADO_ADICIONADO',
    HORARIOS_DIFERENCIADOS_FILTRADO: 'HORARIOS_DIFERENCIADOS_FILTRADO',

    //LOCALIZACAO ACTIONS
    ESTADOS_ENCONTRADOS: 'ESTADOS_ENCONTRADOS',
    ENDERECO_ENCONTRADO: 'ENDERECO_ENCONTRADO',

    //ERRO ACTIONS
    APRESENTAR_ERROS: 'APRESENTAR_ERROS'
}


export default actionTypes;